server:
  port: 13000
spring:
  data:
    mongodb:
      database: zamfind
      host: localhost
      port: 27017
      auto-index-creation: true


  mail:
    host: smtp.gmail.com
    port: 587
    username: askanburi@gmail.com
    password: mpmazxewvudidrbk
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
